name: Deploy and PR Review

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  build-and-deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
      
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Deploy to Production
        run: echo "Deploying to production..." 

  pr-review:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: "Hello from Environment Variable!"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Environment Variable
        run: "echo Environment Variable: ${{ env.MY_ENV_VAR }}"

      - name: Print Secret
        run: "echo Secret: ${{ secrets.MY_SECRET }}"
